# Generated by Django 3.0.5 on 2020-06-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
