# Generated by Django 3.0.5 on 2020-06-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_client_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='price',
            new_name='balance',
        ),
    ]
